config/routes.rb
Rails.application.routes.draw do

  resources :subscribers
  get 'users', to: 'headhunter#users'
  post 'email', to: 'headhunter#email'
  root 'headhunter#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :firstname, :lastname, :email, :presence => true
  validates :email, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  REGEXP_VALID_EMAIL = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :name, presence: true, length: {maximum:50}
  validates :password, presence: true,length: {minimum: 6}
  validates :email, presence: true,
    length: {maximum:255},
    format: {with:REGEXP_VALID_EMAIL},
    uniqueness:{case_sensitive: false}

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/headhunter_controller.rb
class HeadhunterController < ApplicationController
  include HeadhunterHelper

  def index
    oauth = oauthOptions
    @client = OAuth2::Client.new(oauth[:client_id], oauth[:client_secret], :site => oauth[:site])

    if !params[:code] && !session['current_token']
      url = @client.auth_code.authorize_url()
      redirect_to url
    elsif params[:code] && !session['current_token']
      @code = params[:code]
      token = @client.auth_code.get_token(@code)
      token.client.site = oauth[:api_site]
      session['current_token'] = token.to_hash
    end

    @subscribers = Subscriber.where(isNotified: false).limit(80)
  end

  def users
    if !session['current_token'] && !params[:users]
      redirect_to action: 'index'
    end

    if !valid_url? params[:resume_url]
      render html: '<b>Url is not valid</b>'
      return
    end

    oauth = oauthOptions
    @client = OAuth2::Client.new(oauth[:client_id], oauth[:client_secret], :site => oauth[:api_site])
    token = OAuth2::AccessToken.from_hash(@client, session['current_token'])
    if token.expired?
      token = token.refresh!
    end

    resumes_url = params[:resume_url]
    fromPage = params[:fromPage].to_i
    toPage = params[:toPage].to_i
    options = {:fromPage => fromPage, :toPage => toPage}

    docs = getResumeHtml(resumes_url, options)
    @users = getUserInfo(docs)
    PopulateUsersJob.perform_async(token, @users)

    render nothing: true, status: :ok, content_type: "text/html"
  end

  def email
    AccfetcherJob.perform_async

    render nothing: true, status: :ok, content_type: "text/html"
  end

end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :set_subscriber, only: [:show, :edit, :update, :destroy]

  # GET /subscribers
  # GET /subscribers.json
  def index
    @subscribers = Subscriber.all
  end

  # GET /subscribers/1
  # GET /subscribers/1.json
  def show
  end

  # GET /subscribers/new
  def new
    @subscriber = Subscriber.new
  end

  # GET /subscribers/1/edit
  def edit
  end

  # POST /subscribers
  # POST /subscribers.json
  def create
    @subscriber = Subscriber.new(subscriber_params)

    respond_to do |format|
      if @subscriber.save
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully created.' }
        format.json { render :show, status: :created, location: @subscriber }
      else
        format.html { render :new }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscribers/1
  # PATCH/PUT /subscribers/1.json
  def update
    respond_to do |format|
      if @subscriber.update(subscriber_params)
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscriber }
      else
        format.html { render :edit }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribers/1
  # DELETE /subscribers/1.json
  def destroy
    @subscriber.destroy
    respond_to do |format|
      format.html { redirect_to subscribers_url, notice: 'Subscriber was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscriber
      @subscriber = Subscriber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscriber_params
      params.require(:subscriber).permit(:firstname, :lastname, :email, :phone, :isNotified, :id_hh)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/headhunter_helper.rb
module HeadhunterHelper

  def getHHUrls(url, options = {})
    url = URI(url)
    fromPage = options[:fromPage] || 0
    toPage = options[:toPage] || 10

    urls = []
    for page in fromPage..toPage
      query = Rack::Utils.parse_query url.query
      query['page'] = page

      url.query = Rack::Utils.build_query query
      urls.push(URI(url.to_s))
    end

    return urls
  end

  def getResumeHtml(resumes_url, options = {})
    docs = []
    urls = getHHUrls(resumes_url, options)
    uri = urls[0]

    Net::HTTP.start(uri.host, uri.port, :use_ssl => uri.scheme == 'https', :verify_mode => OpenSSL::SSL::VERIFY_NONE) do |http|

      urls.each do |url|
        uri = "#{url.path}?#{url.query}"
        request = Net::HTTP::Get.new uri

        response = http.request request
        html = response.body

        doc = Nokogiri::HTML(html) {|config| config.recover.default_html}
        docs.push(doc)
      end

    end

    return docs
  end

  def getUserInfo(docs)
    users = []
    docs.each do |doc|
      doc.css('a.output__name').each do |link|
        resume_id = link['href'].split('/')[2]
        resume_id = resume_id[/[^\?]+/]
        users.push(resume_id: resume_id)
      end
    end

    return users
  end

  def populateUsers(token, users)
    ua = "Sender/1.0 (filimonov@stforex.com)"

    result = []
    users.each do |user|
      resume_url = '/resumes/' + user[:resume_id].to_s
      response = token.get(resume_url, :headers => { 'User-Agent' => ua }).parsed
      result.push(response)
    end

    users = []
    result.each do |response|
      firstname = response['first_name']
      lastname = response['last_name']
      phone = ''
      email = ''
      id_hh = response["id"]

      response['contact'].each do |contact|
        if contact['type']['id'] == 'cell'
          phone = contact['value']['formatted']
        end

        if contact['type']['id'] == 'email'
          email = contact['value']
        end
      end

      users.push(firstname:firstname, lastname:lastname, email:email, phone:phone, isNotified: false, id_hh: id_hh)

      puts "Creating users..."
      Subscriber.where(users.last).first_or_create(users.last)
    end

    return users
  end

  def valid_url?(uri)
    uri = URI.parse(uri)
    uri && !uri.host.nil?
  rescue URI::InvalidURIError
    false
  rescue NoMethodError
    false
  end

  def oauthOptions
    options = {
      :client_id => 'IMAVQSTQVJKJOHPILL7C5PQV0S22PACA6AJGGHAH7HCOQGLEN94027GFO46737GD',
      :client_secret => 'NQA3UQQFK1F4U2M27RNBVSBF9F9QDQJTKJBD3DARTMCTJD2G9OH6TV908NCO3PN7',
      :site => 'https://hh.ru',
      :api_site => 'https://api.hh.ru'
      # :redirect => 'https://glacial-island-93830.herokuapp.com'
    }

    return options
  end

end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/headhunter/index.html.erb
<section class="task">
  <h2>Резюме кандидатов</h2>
  <%= form_tag("", method: "get", class: "task-actions", id: "candidates") do %>
    <%= number_field_tag('from_page', '0') %>
    <%= number_field_tag('to_page', '10') %>
    <%= text_field_tag(:resume_url, nil, placeholder: "Ссылка на автопоиск") %>
    <%= submit_tag("Загрузить", class: "button") %>
  <% end %>
  <div id="user_list" class="users">
  </div>
</section>
<section class="task">
  <h2>Отправить письма кандидатам</h2>
  <%= form_tag("", method: "get", class: "task-actions", id: "send-emails") do %>
    <%= submit_tag("Отправить всем", class: "button") %>
  <% end %>
  <div class="users">
    <% @subscribers.each do |s| %>
      <div class="user">
        <div><%= s[:email] %></div>
      </div>
    <% end %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelpHunter</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag "application" %>
    <%= yield(:header) if content_for? :header %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/subscribers/_form.html.erb
<%= form_for(subscriber) do |f| %>
  <% if subscriber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>

      <ul>
      <% subscriber.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %>
    <%= f.text_field :firstname %>
  </div>

  <div class="field">
    <%= f.label :lastname %>
    <%= f.text_field :lastname %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :isNotified %>
    <%= f.check_box :isNotified %>
  </div>

  <div class="field">
    <%= f.label :id_hh %>
    <%= f.text_field :id_hh %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscribers/edit.html.erb
<h1>Editing Subscriber</h1>

<%= render 'form', subscriber: @subscriber %>

<%= link_to 'Show', @subscriber %> |
<%= link_to 'Back', subscribers_path %>

app/views/subscribers/index.html.erb
<% content_for :header do -%>
  <style>
    html {
      background: none;
    }
  </style>
<% end -%>
<p id="notice"><%= notice %></p>
<h1>Subscribers</h1>
<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Isnotified</th>
      <th>Id hh</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @subscribers.each do |subscriber| %>
      <tr>
        <td><%= subscriber.firstname %></td>
        <td><%= subscriber.lastname %></td>
        <td><%= subscriber.email %></td>
        <td><%= subscriber.phone %></td>
        <td><%= subscriber.isNotified %></td>
        <td><%= subscriber.id_hh %></td>
        <td><%= link_to 'Show', subscriber %></td>
        <td><%= link_to 'Edit', edit_subscriber_path(subscriber) %></td>
        <td><%= link_to 'Destroy', subscriber, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Subscriber', new_subscriber_path %>

app/views/subscribers/new.html.erb
<h1>New Subscriber</h1>

<%= render 'form', subscriber: @subscriber %>

<%= link_to 'Back', subscribers_path %>

app/views/subscribers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @subscriber.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @subscriber.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @subscriber.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @subscriber.phone %>
</p>

<p>
  <strong>Isnotified:</strong>
  <%= @subscriber.isNotified %>
</p>

<p>
  <strong>Id hh:</strong>
  <%= @subscriber.id_hh %>
</p>

<%= link_to 'Edit', edit_subscriber_path(@subscriber) %> |
<%= link_to 'Back', subscribers_path %>